color0  #08090B
color1  #536E99
color2  #C35995
color3  #6290B0
color4  #66ADCC
color5  #B5A6B8
color6  #E2B6C8
color7  #f1dfe2
color8  #a89c9e
color9  #536E99
color10 #C35995
color11 #6290B0
color12 #66ADCC
color13 #B5A6B8
color14 #E2B6C8
color15 #f1dfe2

cursor                #f1dfe2
cursor_text_color     #08090B
background            #08090B
foreground            #f1dfe2
selection_foreground  #f1dfe2
selection_background  #a89c9e
active_border_color   #C35995
inactive_border_color #08090B
url_color             #C35995

active_tab_foreground   #08090B
active_tab_background   #C35995
inactive_tab_foreground #f1dfe2
inactive_tab_background #08090B
