-- Generated by nwg-displays on 2026-04-05, converted to Lua

hl.monitor({ output = "DP-2", mode = "1920x1080@165.0", position = "0x360",   scale = 1.0 })
hl.monitor({ output = "DP-3", mode = "2560x1440@180.0", position = "1920x0",  scale = 1.0 })
