general {
    lock_cmd = pidof hyprlock || hyprlock   # prevent multiple hyprlock instances
    before_sleep_cmd = loginctl lock-session # lock before suspend
    after_sleep_cmd = hyprctl dispatch dpms on # turn screen back on after wake
    ignore_dbus_inhibit = false              # respect apps like Firefox/Steam
}

# 1. Dim screen after 2.5 min
listener {
    timeout = 150
    on-timeout = brightnessctl -s set 10%   # dim to 10%, save current brightness
    on-resume  = brightnessctl -r            # restore brightness on activity
}

# 2. Lock screen after 5 min
listener {
    timeout = 300
    on-timeout = loginctl lock-session
}

# 3. Turn off display after 5.5 min
listener {
    timeout = 330
    on-timeout = hyprctl dispatch dpms off
    on-resume  = hyprctl dispatch dpms on
}

# 4. Suspend after 30 min
listener {
    timeout = 1800
    on-timeout = systemctl suspend
}
