# cyberdream - btop theme
# Mapped from isleap's waybar theme

theme[main_bg]="#16181a"
theme[main_fg]="#ffffff"
theme[title]="#6699ff"
theme[hi_fg]="#6699ff"
theme[selected_bg]="#32363b"
theme[selected_fg]="#ffffff"
theme[inactive_fg]="#5e6370"
theme[graph_text]="#ffffff"
theme[meter_bg]="#282b2f"
theme[proc_misc]="#5ef1ff"

theme[cpu_start]="#5eff6c"
theme[cpu_mid]="#ffff85"
theme[cpu_end]="#ff6e6e"

theme[free_start]="#5eff6c"
theme[free_mid]="#ffff85"
theme[free_end]="#ff6e6e"

theme[cached_start]="#5ef1ff"
theme[cached_mid]="#6699ff"
theme[cached_end]="#df80ff"

theme[available_start]="#5eff6c"
theme[available_mid]="#ffff85"
theme[available_end]="#ff6e6e"

theme[used_start]="#5eff6c"
theme[used_mid]="#ffff85"
theme[used_end]="#ff6e6e"

theme[download_start]="#5ef1ff"
theme[download_mid]="#6699ff"
theme[download_end]="#df80ff"

theme[upload_start]="#ffbd5e"
theme[upload_mid]="#ffff85"
theme[upload_end]="#ff6e6e"

theme[process_start]="#5eff6c"
theme[process_mid]="#ffff85"
theme[process_end]="#ff6e6e"

theme[div_line]="#32363b"
theme[box_border]="#32363b"
theme[box_title]="#6699ff"
theme[box_hi]="#df80ff"
