# dracula - btop theme
# Mapped from isleap's waybar theme

theme[main_bg]="#282a36"
theme[main_fg]="#f8f8f2"
theme[title]="#bd93f9"
theme[hi_fg]="#bd93f9"
theme[selected_bg]="#44475a"
theme[selected_fg]="#f8f8f2"
theme[inactive_fg]="#6272a4"
theme[graph_text]="#f8f8f2"
theme[meter_bg]="#343746"
theme[proc_misc]="#8be9fd"

theme[cpu_start]="#50fa7b"
theme[cpu_mid]="#f1fa8c"
theme[cpu_end]="#ff5555"

theme[free_start]="#50fa7b"
theme[free_mid]="#f1fa8c"
theme[free_end]="#ff5555"

theme[cached_start]="#8be9fd"
theme[cached_mid]="#6272a4"
theme[cached_end]="#bd93f9"

theme[available_start]="#50fa7b"
theme[available_mid]="#f1fa8c"
theme[available_end]="#ff5555"

theme[used_start]="#50fa7b"
theme[used_mid]="#f1fa8c"
theme[used_end]="#ff5555"

theme[download_start]="#8be9fd"
theme[download_mid]="#6272a4"
theme[download_end]="#bd93f9"

theme[upload_start]="#ffb86c"
theme[upload_mid]="#f1fa8c"
theme[upload_end]="#ff5555"

theme[process_start]="#50fa7b"
theme[process_mid]="#f1fa8c"
theme[process_end]="#ff5555"

theme[div_line]="#44475a"
theme[box_border]="#44475a"
theme[box_title]="#bd93f9"
theme[box_hi]="#8be9fd"
