# gruvbox - btop theme
# Mapped from isleap's waybar theme

theme[main_bg]="#282828"
theme[main_fg]="#ebdbb2"
theme[title]="#fabd2f"
theme[hi_fg]="#fabd2f"
theme[selected_bg]="#665c54"
theme[selected_fg]="#ebdbb2"
theme[inactive_fg]="#a89984"
theme[graph_text]="#ebdbb2"
theme[meter_bg]="#504945"
theme[proc_misc]="#8ec07c"

theme[cpu_start]="#b8bb26"
theme[cpu_mid]="#fabd2f"
theme[cpu_end]="#fb4934"

theme[free_start]="#b8bb26"
theme[free_mid]="#fabd2f"
theme[free_end]="#fb4934"

theme[cached_start]="#8ec07c"
theme[cached_mid]="#83a598"
theme[cached_end]="#d3869b"

theme[available_start]="#b8bb26"
theme[available_mid]="#fabd2f"
theme[available_end]="#fb4934"

theme[used_start]="#b8bb26"
theme[used_mid]="#fabd2f"
theme[used_end]="#fb4934"

theme[download_start]="#8ec07c"
theme[download_mid]="#83a598"
theme[download_end]="#d3869b"

theme[upload_start]="#fe8019"
theme[upload_mid]="#fabd2f"
theme[upload_end]="#fb4934"

theme[process_start]="#b8bb26"
theme[process_mid]="#fabd2f"
theme[process_end]="#fb4934"

theme[div_line]="#665c54"
theme[box_border]="#665c54"
theme[box_title]="#fabd2f"
theme[box_hi]="#83a598"
