# oxocarbon - btop theme
# Mapped from isleap's waybar theme

theme[main_bg]="#161616"
theme[main_fg]="#f2f4f8"
theme[title]="#78a9ff"
theme[hi_fg]="#78a9ff"
theme[selected_bg]="#333333"
theme[selected_fg]="#f2f4f8"
theme[inactive_fg]="#525252"
theme[graph_text]="#f2f4f8"
theme[meter_bg]="#252525"
theme[proc_misc]="#3ddbd9"

theme[cpu_start]="#42be65"
theme[cpu_mid]="#fddc69"
theme[cpu_end]="#ff7eb6"

theme[free_start]="#42be65"
theme[free_mid]="#fddc69"
theme[free_end]="#ff7eb6"

theme[cached_start]="#3ddbd9"
theme[cached_mid]="#78a9ff"
theme[cached_end]="#be95ff"

theme[available_start]="#42be65"
theme[available_mid]="#fddc69"
theme[available_end]="#ff7eb6"

theme[used_start]="#42be65"
theme[used_mid]="#fddc69"
theme[used_end]="#ff7eb6"

theme[download_start]="#3ddbd9"
theme[download_mid]="#78a9ff"
theme[download_end]="#be95ff"

theme[upload_start]="#ff6f00"
theme[upload_mid]="#fddc69"
theme[upload_end]="#ff7eb6"

theme[process_start]="#42be65"
theme[process_mid]="#fddc69"
theme[process_end]="#ff7eb6"

theme[div_line]="#333333"
theme[box_border]="#333333"
theme[box_title]="#78a9ff"
theme[box_hi]="#be95ff"
