# papercolor - btop theme
# Mapped from isleap's waybar theme

theme[main_bg]="#eeeeee"
theme[main_fg]="#444444"
theme[title]="#0087af"
theme[hi_fg]="#0087af"
theme[selected_bg]="#b8b8b8"
theme[selected_fg]="#444444"
theme[inactive_fg]="#878787"
theme[graph_text]="#444444"
theme[meter_bg]="#d0d0d0"
theme[proc_misc]="#005f87"

theme[cpu_start]="#008700"
theme[cpu_mid]="#d75f00"
theme[cpu_end]="#af0000"

theme[free_start]="#008700"
theme[free_mid]="#d75f00"
theme[free_end]="#af0000"

theme[cached_start]="#005f87"
theme[cached_mid]="#0087af"
theme[cached_end]="#8700af"

theme[available_start]="#008700"
theme[available_mid]="#d75f00"
theme[available_end]="#af0000"

theme[used_start]="#008700"
theme[used_mid]="#d75f00"
theme[used_end]="#af0000"

theme[download_start]="#005f87"
theme[download_mid]="#0087af"
theme[download_end]="#8700af"

theme[upload_start]="#d75f00"
theme[upload_mid]="#d75f00"
theme[upload_end]="#af0000"

theme[process_start]="#008700"
theme[process_mid]="#d75f00"
theme[process_end]="#af0000"

theme[div_line]="#b8b8b8"
theme[box_border]="#b8b8b8"
theme[box_title]="#0087af"
theme[box_hi]="#8700af"
