# Catppuccin Latte

background              #eff1f5
foreground              #4c4f69
selection_background    #acb0be
selection_foreground    #4c4f69
cursor                  #8839ef
cursor_text_color       #eff1f5

# Black
color0  #5c5f77
color8  #6c6f85

# Red
color1  #d20f39
color9  #d20f39

# Green
color2  #40a02b
color10 #40a02b

# Yellow
color3  #df8e1d
color11 #df8e1d

# Blue
color4  #1e66f5
color12 #1e66f5

# Magenta
color5  #8839ef
color13 #8839ef

# Cyan
color6  #04a5e5
color14 #04a5e5

# White
color7  #4c4f69
color15 #4c4f69

url_color #1e66f5
