# Catppuccin Frappe

background              #303446
foreground              #c6d0f5
selection_background    #51576d
selection_foreground    #c6d0f5
cursor                  #ca9ee6
cursor_text_color       #303446

# Black
color0  #51576d
color8  #626880

# Red
color1  #e78284
color9  #e78284

# Green
color2  #a6d189
color10 #a6d189

# Yellow
color3  #e5c890
color11 #e5c890

# Blue
color4  #8caaee
color12 #8caaee

# Magenta
color5  #ca9ee6
color13 #ca9ee6

# Cyan
color6  #85c1dc
color14 #85c1dc

# White
color7  #b5bfe2
color15 #c6d0f5

url_color #8caaee
