# Cyberdream

background              #16181a
foreground              #ffffff
selection_background    #32363b
selection_foreground    #ffffff
cursor                  #df80ff
cursor_text_color       #16181a

# Black
color0  #16181a
color8  #5e6370

# Red
color1  #ff6e6e
color9  #ff6e6e

# Green
color2  #5eff6c
color10 #5eff6c

# Yellow
color3  #ffff85
color11 #ffff85

# Blue
color4  #6699ff
color12 #6699ff

# Magenta
color5  #df80ff
color13 #df80ff

# Cyan
color6  #5ef1ff
color14 #5ef1ff

# White
color7  #ffffff
color15 #ffffff

url_color #5ef1ff
