# Dracula Light

background              #f8f8f2
foreground              #282a36
selection_background    #d0d0dc
selection_foreground    #282a36
cursor                  #7c4dbd
cursor_text_color       #f8f8f2

# Black
color0  #44475a
color8  #6272a4

# Red
color1  #cc0000
color9  #cc0000

# Green
color2  #007a00
color10 #007a00

# Yellow
color3  #8b8b00
color11 #8b8b00

# Blue
color4  #4040cc
color12 #4040cc

# Magenta
color5  #7c4dbd
color13 #7c4dbd

# Cyan
color6  #007b8a
color14 #007b8a

# White
color7  #282a36
color15 #282a36

url_color #4040cc
