# E-Ink Dark

background              #1a1a1a
foreground              #e8e8e8
selection_background    #383838
selection_foreground    #e8e8e8
cursor                  #e8e8e8
cursor_text_color       #1a1a1a

# Black
color0  #1a1a1a
color8  #555555

# Red
color1  #cc3333
color9  #cc3333

# Green
color2  #336633
color10 #336633

# Yellow
color3  #888800
color11 #888800

# Blue
color4  #334466
color12 #334466

# Magenta
color5  #553366
color13 #553366

# Cyan
color6  #336666
color14 #336666

# White
color7  #e8e8e8
color15 #e8e8e8

url_color #334466
