# Rosé Pine Moon
# https://rosepinetheme.com

background              #232136
foreground              #e0def4
selection_background    #44415a
selection_foreground    #e0def4
cursor                  #c4a7e7
cursor_text_color       #232136

# Black
color0  #393552
color8  #6e6a86

# Red (Love)
color1  #eb6f92
color9  #eb6f92

# Green (Pine)
color2  #3e8fb0
color10 #3e8fb0

# Yellow (Gold)
color3  #f6c177
color11 #f6c177

# Blue (Pine)
color4  #3e8fb0
color12 #3e8fb0

# Magenta (Iris)
color5  #c4a7e7
color13 #c4a7e7

# Cyan (Foam)
color6  #9ccfd8
color14 #9ccfd8

# White
color7  #e0def4
color15 #e0def4

# URL color
url_color #c4a7e7
