# Tokyo Day

background              #e1e2e7
foreground              #3760bf
selection_background    #b4b5c0
selection_foreground    #3760bf
cursor                  #2e7de9
cursor_text_color       #e1e2e7

# Black
color0  #b4b5c0
color8  #848cb5

# Red
color1  #f52a65
color9  #f52a65

# Green
color2  #587539
color10 #587539

# Yellow
color3  #8c6c3e
color11 #8c6c3e

# Blue
color4  #2e7de9
color12 #2e7de9

# Magenta
color5  #9854f1
color13 #9854f1

# Cyan
color6  #007197
color14 #007197

# White
color7  #3760bf
color15 #3760bf

url_color #2e7de9
